- name: Install common packages
  ansible.builtin.dnf:
    pkg:
      - mariadb
      - mariadb-server
  become: true
- name: Write mariadb dat151 config
  ansible.builtin.template:
    src: templates/dat151.cnf
    dest: /etc/my.cnf.d
    mode: "0644"
  become: true
- name: Mariadb service
  ansible.builtin.systemd_service:
    name: mariadb
    enabled: true
    state: started
  become: true
- name: Open firewall for mariadb
  ansible.posix.firewalld:
    service: mysql
    state: enabled
    permanent: true
  become: true
